services:
  web:
    build: .
    container_name: web

    ports:
      - "8000:8000"

    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/

        - action: rebuild
          path: ./uv.lock
